# Import

In [1]:
import numpy as np
import pandas as pd
from news_utils import read_csv_file
from news_crawling import news_crawler
from datetime import datetime

import warnings # FutureWarning 안보이게
warnings.simplefilter(action='ignore', category=DeprecationWarning)

# URL 리스트 받아오기

In [2]:
url_list = read_csv_file()
url_list[:7]

urls_230628.csv 로부터 csv파일 불러오기 성공
총 URL 수 : 599

['https://n.news.naver.com/mnews/article/003/0011937770?sid=105',
 'https://n.news.naver.com/mnews/article/421/0006893135?sid=105',
 'https://n.news.naver.com/mnews/article/018/0005517609?sid=105',
 'https://n.news.naver.com/mnews/article/003/0011939677?sid=105',
 'https://n.news.naver.com/mnews/article/028/0002645782?sid=105',
 'https://n.news.naver.com/mnews/article/277/0005278661?sid=105',
 'https://n.news.naver.com/mnews/article/018/0005518433?sid=105']

In [3]:
df = pd.DataFrame({'URL':url_list, '신문사':np.nan, '기자명':np.nan, '제목':np.nan, '본문':np.nan,
                   '날짜':np.nan, '연':np.nan, '월':np.nan, '일':np.nan, '요일':np.nan})
df

,URL,신문사,기자명,제목,본문,날짜,연,월,일,요일
0,https://n.news.naver.com/mnews/article/003/001...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://n.news.naver.com/mnews/article/421/000...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://n.news.naver.com/mnews/article/018/000...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://n.news.naver.com/mnews/article/003/001...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://n.news.naver.com/mnews/article/028/000...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
594,https://n.news.naver.com/mnews/article/584/000...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
595,https://n.news.naver.com/mnews/article/138/000...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
596,https://n.news.naver.com/mnews/article/215/000...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
597,https://n.news.naver.com/mnews/article/008/000...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598,https://n.news.naver.com/mnews/article/022/000...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 필요한 정보 스크래핑 하여 df에적재 및 df_yymmdd.csv로저장

In [4]:
df = news_crawler(df)

100%|██████████| 599/599 [08:41<00:00,  1.15it/s]

In [5]:
today = datetime.today().strftime('%y%m%d')
df.to_csv('df_'+today+'.csv', index=False)

display(df.head(3))
display(df.tail(3))

,URL,신문사,기자명,제목,본문,날짜,연,월,일,요일
0,https://n.news.naver.com/mnews/article/003/001...,뉴시스,윤현성,다누리 수명 3배 연장…2025년 12월까지 달탐사,"다누리, 임무운영 기간 1년→3년 연장\n성공적 항행으로 연료 30㎏ 절약…본체 부...",2023-06-27,2023,6,27,1
1,https://n.news.naver.com/mnews/article/421/000...,뉴스1,김태진,"KAIST, 맥신 나노기술로 세탁 가능한 투명 플렉시블 OLED 개발",맥신 기반 OLED 디스플레이 개념도(KAIST 제공)/뉴스1\n\n\n(대전ㆍ충남...,2023-06-28,2023,6,28,2
2,https://n.news.naver.com/mnews/article/003/001...,뉴시스,최은수,"컴투스홀딩스 '제노니아', 인기 게임 1위·애플 매출 2위",출시 하루 만에 구글 플레이 및 애플 앱스토어 인기 게임 1위\n컴투스홀딩스는 자사...,2023-06-28,2023,6,28,2

,URL,신문사,기자명,제목,본문,날짜,연,월,일,요일
217,https://n.news.naver.com/mnews/article/366/000...,조선비즈,정보없음,"“외산과 붙어도 자신 있다” 생성형 AI 출격 앞둔 네이버… 하이퍼클로바X, 8월 ...",“바드나 챗GPT와 비교해도 성능 괜찮다 느낄 것”\n”사내 테스트 반응 아주 좋아...,2023-06-27,2023,6,27,1
218,https://n.news.naver.com/mnews/article/081/000...,서울신문,유용하,‘노출의 계절’ 날씬한 몸매 가지려면…[달콤한 사이언스],다이어트만으로는 체중 감량 효과 낮아\n주6회 1시간씩 운동 병행해야 다이어트 효과...,2023-06-27,2023,6,27,1
219,https://n.news.naver.com/mnews/article/025/000...,중앙일보,여성국,펫팸족 1300만명 시대…AI로 ‘댕댕이 건강’ 체크한다,펫테크가 통신사의 새 먹거리로 떠오르고 있다. SK텔레콤이 지난해 출시한 AI 기반...,2023-06-27,2023,6,27,1